# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - skade-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_44a8e737242941c0a5b283e72e409fcf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb17a902dfb44f979896c32e3039c06c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_44a8e737242941c0a5b283e72e409fcf }}/skade-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'skade-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_24db947ff68040a09df9324d9fbc6437 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_44a8e737242941c0a5b283e72e409fcf }}/skade-service:${{ github.sha }}'